# Generated by Django 4.0.4 on 2022-05-19 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('alias', models.CharField(blank=True, max_length=30, verbose_name='Псевдоним')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес')),
                ('card_number', models.IntegerField(blank=True, null=True, verbose_name='Номер карты')),
                ('is_ru', models.BooleanField(default=True, verbose_name='Русский язык')),
                ('is_male', models.BooleanField(default=True, verbose_name='Мужской пол')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, choices=[(None, 'Выберите город'), ('1', 'Одесса'), ('2', 'Днепр'), ('3', 'Чернигов'), ('4', 'Харьков'), ('5', 'Житомир'), ('6', 'Полтава'), ('7', 'Херсон'), ('8', 'Киев'), ('9', 'Запорожье'), ('10', 'Луганск'), ('11', 'Донецк'), ('12', 'Винница'), ('13', 'Кировоград'), ('14', 'Николаев'), ('15', 'Суммы'), ('16', 'Львов'), ('17', 'Черкасы'), ('18', 'Хмельницк'), ('19', 'Волынь'), ('20', 'Ровно'), ('21', 'Ивано-Франковск'), ('22', 'Тернополь'), ('23', 'Закарпатье'), ('24', 'Черновцы')], max_length=2, verbose_name='Город')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
