# Generated by Django 4.0.4 on 2022-05-23 12:10

from django.db import migrations
import users.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_is_male_alter_userprofile_is_ru'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', users.manager.CustomUserManager()),
            ],
        ),
    ]
