# Generated by Django 4.0.4 on 2022-05-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, choices=[(None, 'Выберите город'), ('Одесса', 'Одесса'), ('Днепр', 'Днепр'), ('Чернигов', 'Чернигов'), ('Харьков', 'Харьков'), ('Житомир', 'Житомир'), ('Полтава', 'Полтава'), ('Херсон', 'Херсон'), ('Киев', 'Киев'), ('Запорожье', 'Запорожье'), ('Луганск', 'Луганск'), ('Донецк', 'Донецк'), ('Винница', 'Винница'), ('Кировоград', 'Кировоград'), ('Николаев', 'Николаев'), ('Суммы', 'Суммы'), ('Львов', 'Львов'), ('Черкасы', 'Черкасы'), ('Хмельницк', 'Хмельницк'), ('Волынь', 'Волынь'), ('Ровно', 'Ровно'), ('Ивано-Франковск', 'Ивано-Франковск'), ('Тернополь', 'Тернополь'), ('Закарпатье', 'Закарпатье'), ('Черновцы', 'Черновцы')], max_length=20, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
