version: '3.7'

services:
  web:
    build: .
    command: make startapp
    volumes:
      - static_volume:/usr/src/cinema/static
      - media_volume:/usr/src/cinema/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/cinema/static
      - media_volume:/usr/src/cinema/media
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A cinema worker --loglevel=info
    ports:
      - 587:587
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:


