# Generated by Django 4.0.4 on 2022-04-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_film_type_film_type_2d_film_type_3d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='logo',
            field=models.ImageField(upload_to='gallery/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='top_banner',
            field=models.ImageField(upload_to='gallery/', verbose_name='Верхний баннер'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=models.ImageField(upload_to='gallery/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='film',
            name='main_picture',
            field=models.ImageField(upload_to='gallery/', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='scheme',
            field=models.ImageField(upload_to='gallery/', verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='top_banner',
            field=models.ImageField(upload_to='gallery/', verbose_name='Верхний баннер'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='newsorprom',
            name='main_picture',
            field=models.ImageField(upload_to='gallery/', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='page',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Главная картинка'),
        ),
    ]
