# Generated by Django 4.0.4 on 2022-04-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cinema_logo_alter_cinema_top_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название кинотеатра'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='top_banner',
            field=models.ImageField(upload_to='gallery/', verbose_name='Фото верхнего баннера'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='coordinate',
            field=models.URLField(verbose_name='Координаты для карты'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=models.ImageField(upload_to='gallery/', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.cinema', verbose_name='Название кинотеатра'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=models.URLField(verbose_name='Ссылка на трейлер'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(verbose_name='Описание зала'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_number',
            field=models.IntegerField(verbose_name='Номер зала'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='scheme',
            field=models.ImageField(upload_to='gallery/', verbose_name='Схема зала'),
        ),
        migrations.AlterField(
            model_name='newsorprom',
            name='link_to_video',
            field=models.URLField(verbose_name='Ссылка на видео'),
        ),
    ]
