# Generated by Django 4.0.4 on 2022-05-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_hall_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='condition_ru',
            field=models.TextField(null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='condition_uk',
            field=models.TextField(null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название кинотеатра'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_uk',
            field=models.CharField(max_length=30, null=True, verbose_name='Название кинотеатра'),
        ),
    ]
