# Generated by Django 4.0.4 on 2022-05-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_hall_is_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание зала'),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание зала'),
        ),
    ]
