# Generated by Django 4.0.4 on 2022-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_hall_description_ru_hall_description_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsorprom',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newsorprom',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newsorprom',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='newsorprom',
            name='name_uk',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
    ]
