# Generated by Django 4.0.4 on 2022-05-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_contact_address_ru_remove_contact_address_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_contact',
            field=models.BooleanField(default=False, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
    ]
