# Generated by Django 4.0.4 on 2022-05-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_page_is_contact_page_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_base',
            field=models.BooleanField(default=False, verbose_name='Основная страница'),
        ),
    ]
