# Generated by Django 4.0.4 on 2022-05-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_page_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='coordinate',
            field=models.CharField(max_length=128, verbose_name='Координаты для карты'),
        ),
    ]
