# Generated by Django 4.0.4 on 2022-05-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_contact_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bg', models.BooleanField(default=False, verbose_name='Просто фон')),
                ('is_photo_bg', models.BooleanField(default=True, verbose_name='Фото на фоне')),
                ('photo', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('speed', models.CharField(choices=[('5с', 5000), ('10с', 10000), ('15с', 15000)], default='5с', max_length=3, verbose_name='Скорость')),
                ('is_main', models.BooleanField(default=True, verbose_name='Главная верх')),
            ],
            options={
                'verbose_name': 'Карусель',
                'verbose_name_plural': 'Карусели',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Картинка')),
                ('url', models.URLField(verbose_name='URL')),
                ('text', models.CharField(blank=True, max_length=20, null=True, verbose_name='Текст')),
                ('is_main', models.BooleanField(default=True, verbose_name='Главный слайд')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.DeleteModel(
            name='Background',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AddField(
            model_name='carousel',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.slide', verbose_name='Слайд'),
        ),
    ]
