# Generated by Django 4.0.4 on 2022-05-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_carousel_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='speed',
            field=models.CharField(choices=[(5000, '5с'), (10000, '10с'), (15000, '15с')], default=5000, max_length=5, verbose_name='Скорость'),
        ),
    ]
