# Generated by Django 4.0.4 on 2022-05-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_banner_is_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='text',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Текст'),
        ),
    ]
