# Generated by Django 4.0.4 on 2022-05-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_mailing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(default=1, max_length=64, verbose_name='Название новости'),
            preserve_default=False,
        ),
    ]
