# Generated by Django 4.0.4 on 2022-05-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_mailing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='letter',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Письмо'),
        ),
    ]
