# Generated by Django 4.0.4 on 2022-06-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_mailing_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='coordinate',
            field=models.CharField(max_length=256, verbose_name='Координаты для карты'),
        ),
    ]
