# Generated by Django 4.0.4 on 2022-06-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_contact_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='coordinate',
            field=models.CharField(max_length=512, verbose_name='Координаты для карты'),
        ),
    ]
