# Generated by Django 4.0.4 on 2022-06-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_contact_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=models.CharField(max_length=128, verbose_name='Ссылка на трейлер'),
        ),
    ]
