# Generated by Django 4.0.4 on 2022-06-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_film_trailer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
