# Generated by Django 4.0.4 on 2022-06-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='cost',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
